version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  post_build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew clean build
      - cp build/libs/*.jar application.jar
artifacts:
  files:
    - application.jar
    - .ebextensions/**/*
    - Procfile